routes:
  "gitsense.dyastin.tech": 
    routes:
      "/api": "http://localhost:4000"
      "/": "http://localhost:4001"
    rate_limit:
      burst: 100
      rate: 50
      cooldown: 60000
  "filespace.dyastin.tech":
    routes:
      "/api/v2": "http://localhost:3004"
      "/": "http://localhost:5005"
    rate_limit:
      burst: 100
      rate: 50
      cooldown: 60000
  "omnisense.dyastin.tech":
    routes:
      "/": "http://localhost:4004"
    rate_limit:
      burst: 100
      rate: 50
      cooldown: 60000
  "filmpin.dyastin.tech":
    routes:
      "/api": "http://localhost:5001"
      "/": "http://localhost:5002"
    rate_limit:
      burst: 100
      rate: 50
      cooldown: 60000
  "metrics.dyastin.tech":
    routes:
      "/": "http://localhost:3000"
    rate_limit:
      burst: 100
      rate: 50
      cooldown: 60000

email: "mail@dyastin.tech"

rate_limit:
  burst: 100
  rate: 50
  cooldown: 60000
