routes:
  "gitsense.dyastin.tech/api": "http://localhost:4000"
  "gitsense.dyastin.tech": "http://localhost:4001"
  "filespace.dyastin.tech/api/v2": "http://localhost:3004"
  "filespace.dyastin.tech": "http://localhost:5005"
  "omnisense.dyastin.tech": "http://localhost:4004"
  "filmpin.dyastin.tech/api": "http://localhost:5001"
  "filmpin.dyastin.tech": "http://localhost:5002"

domains:
  - "dyastin.tech"
  - "gitsense.dyastin.tech"
  - "filespace.dyastin.tech"
  - "omnisense.dyastin.tech"
  - "filmpin.dyastin.tech"

rate_limit:
  burst: 25
  rate: 50
  cooldown: 60000
